[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Initialize Hitman rotation
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "reset_castle_card()"
position = "after"
payload = "SMODS.Centers.j_pencil_killer:reset_target()"
match_indent = true
